name: Elixir Phoenix Release

on:
  push:
    - 'v*' # trigger on version tags
  workflow_dispatch:

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
      with:
        elixir-version: '1.16' 
        otp-version: '26.0'
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: Clean to rule out incremental build as a source of flakiness
      if: github.run_attempt != '1'
      run: |
        mix deps.clean --all
        mix clean
      shell: sh
    - name: Install dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get --only prod
    - name: Build assets
      run: MIX_ENV=prod mix assets.deploy
    - name: Build release
        env: SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        run: |
          mix phx.gen.release 
          MIX_ENV=prod mix release
    - name: Upload release artifact
          uses: actions/upload-artifact@v3
        with:
          name: einwortspiel_release
          path: _build/prod/rel/einwortspiel
